# Server:
server:
  port: 9090
  servlet:
    context-path: /empApp
# Database
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test_db
      username: srkontham
      password: password
# JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# Logging
logging:
  level:
    com:
      srk: debug


